<?php

namespace ContainerFiskiGn;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Ggdhd79Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.ggdhd79' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/src/Application/Command/CommandHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Notification/Application/Command/ChangeNotificationCommandHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Notification/Application/Expander/NotificationDtoExpanderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Notification/Application/Expander/NotificationDtoExpander.php';

        return $container->privates['.messenger.handler_descriptor.ggdhd79'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Notification\Application\Command\ChangeNotificationCommandHandler(new \App\Notification\Expander\NotificationDtoExpander()), []);
    }
}
