<?php

namespace ContainerFiskiGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1M7EDLOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1M7EDLO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1M7EDLO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CallBackController::callBackListID' => ['privates', '.service_locator.ED.Gtlv', 'get_ServiceLocator_ED_GtlvService', true],
            'App\\Controller\\CallBackController::index' => ['privates', '.service_locator.ED.Gtlv', 'get_ServiceLocator_ED_GtlvService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.rqj6Qk0', 'get_ServiceLocator_Rqj6Qk0Service', true],
            'App\\Controller\\ExchangeController::create' => ['privates', '.service_locator.u1DotUV', 'get_ServiceLocator_U1DotUVService', true],
            'App\\Controller\\LoginController::messageCheck' => ['privates', '.service_locator.11jF2Yh', 'get_ServiceLocator_11jF2YhService', true],
            'App\\Controller\\LoginController::messageLogin' => ['privates', '.service_locator.11jF2Yh', 'get_ServiceLocator_11jF2YhService', true],
            'App\\Controller\\MixingOrderController::createMixingOrder' => ['privates', '.service_locator.u1DotUV', 'get_ServiceLocator_U1DotUVService', true],
            'App\\Controller\\PriceController::index' => ['privates', '.service_locator.wUi70Dc', 'get_ServiceLocator_WUi70DcService', true],
            'App\\Controller\\RegistrationController::index' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\WalletsController::DeleteWallet' => ['privates', '.service_locator.oMohtWn', 'get_ServiceLocator_OMohtWnService', true],
            'App\\Controller\\WalletsController::getRandomSeedPhraze' => ['privates', '.service_locator.oMohtWn', 'get_ServiceLocator_OMohtWnService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CallBackController:callBackListID' => ['privates', '.service_locator.ED.Gtlv', 'get_ServiceLocator_ED_GtlvService', true],
            'App\\Controller\\CallBackController:index' => ['privates', '.service_locator.ED.Gtlv', 'get_ServiceLocator_ED_GtlvService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.rqj6Qk0', 'get_ServiceLocator_Rqj6Qk0Service', true],
            'App\\Controller\\ExchangeController:create' => ['privates', '.service_locator.u1DotUV', 'get_ServiceLocator_U1DotUVService', true],
            'App\\Controller\\LoginController:messageCheck' => ['privates', '.service_locator.11jF2Yh', 'get_ServiceLocator_11jF2YhService', true],
            'App\\Controller\\LoginController:messageLogin' => ['privates', '.service_locator.11jF2Yh', 'get_ServiceLocator_11jF2YhService', true],
            'App\\Controller\\MixingOrderController:createMixingOrder' => ['privates', '.service_locator.u1DotUV', 'get_ServiceLocator_U1DotUVService', true],
            'App\\Controller\\PriceController:index' => ['privates', '.service_locator.wUi70Dc', 'get_ServiceLocator_WUi70DcService', true],
            'App\\Controller\\RegistrationController:index' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\WalletsController:DeleteWallet' => ['privates', '.service_locator.oMohtWn', 'get_ServiceLocator_OMohtWnService', true],
            'App\\Controller\\WalletsController:getRandomSeedPhraze' => ['privates', '.service_locator.oMohtWn', 'get_ServiceLocator_OMohtWnService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CallBackController::callBackListID' => '?',
            'App\\Controller\\CallBackController::index' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\ExchangeController::create' => '?',
            'App\\Controller\\LoginController::messageCheck' => '?',
            'App\\Controller\\LoginController::messageLogin' => '?',
            'App\\Controller\\MixingOrderController::createMixingOrder' => '?',
            'App\\Controller\\PriceController::index' => '?',
            'App\\Controller\\RegistrationController::index' => '?',
            'App\\Controller\\WalletsController::DeleteWallet' => '?',
            'App\\Controller\\WalletsController::getRandomSeedPhraze' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CallBackController:callBackListID' => '?',
            'App\\Controller\\CallBackController:index' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\ExchangeController:create' => '?',
            'App\\Controller\\LoginController:messageCheck' => '?',
            'App\\Controller\\LoginController:messageLogin' => '?',
            'App\\Controller\\MixingOrderController:createMixingOrder' => '?',
            'App\\Controller\\PriceController:index' => '?',
            'App\\Controller\\RegistrationController:index' => '?',
            'App\\Controller\\WalletsController:DeleteWallet' => '?',
            'App\\Controller\\WalletsController:getRandomSeedPhraze' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
