<?php

namespace ContainerFiskiGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OMohtWnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oMohtWn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oMohtWn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'del' => ['privates', 'App\\Generator\\Del', 'getDelService', true],
        ], [
            'del' => 'App\\Generator\\Del',
        ]);
    }
}
