<?php

namespace ContainerFiskiGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMixingOrderControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MixingOrderController' shared autowired service.
     *
     * @return \App\Controller\MixingOrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MixingOrderController.php';

        $container->services['App\\Controller\\MixingOrderController'] = $instance = new \App\Controller\MixingOrderController(($container->services['doctrine'] ?? $container->load('getDoctrineService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\MixingOrderController', $container));

        return $instance;
    }
}
