<?php

namespace ContainerFiskiGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Generator\Mail' shared autowired service.
     *
     * @return \App\Generator\Mail
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Generator/Mail.php';

        return $container->privates['App\\Generator\\Mail'] = new \App\Generator\Mail(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
