<?php

namespace ContainerFiskiGn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWalletsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WalletsController' shared autowired service.
     *
     * @return \App\Controller\WalletsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/WalletsController.php';

        $container->services['App\\Controller\\WalletsController'] = $instance = new \App\Controller\WalletsController(($container->services['doctrine'] ?? $container->load('getDoctrineService')));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\WalletsController', $container));

        return $instance;
    }
}
