version: "3.5"
services:
  temporal:
    env_file:
      - .env
    image: temporalio/auto-setup:1.18.5
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
    ports:
      - 7233:7233

  temporal-admin-tools:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.18.5
    stdin_open: true
    tty: true

  temporal-web:
    image: temporalio/web:1.15.0
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    ports:
      - 8080:8080

  php-back:
    build:
      context: .
    command: [ "/usr/local/bin/wait-for-temporal.sh", "temporal", "/usr/local/bin/rr", "serve", "/var/app/.rr.yaml" ]
    environment:
      TEMPORAL_CLI_ADDRESS: "temporal:7233"