<?php

namespace Container1nJgEou;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCryptoCompareService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Integration\CryptoCompare' shared autowired service.
     *
     * @return \App\Integration\CryptoCompare
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Integration/CryptoCompare.php';

        return $container->privates['App\\Integration\\CryptoCompare'] = new \App\Integration\CryptoCompare();
    }
}
