<?php

namespace ContainerHaa1esI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Generator\Del' shared autowired service.
     *
     * @return \App\Generator\Del
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Generator/Del.php';

        return $container->privates['App\\Generator\\Del'] = new \App\Generator\Del();
    }
}
