<?php

namespace ContainerU7d8Zxg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommand_Bus_Middleware_DoctrineTransactionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'command.bus.middleware.doctrine_transaction' shared service.
     *
     * @return \Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/Messenger/AbstractDoctrineMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/Messenger/DoctrineTransactionMiddleware.php';

        return $container->privates['command.bus.middleware.doctrine_transaction'] = new \Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
