<?php

namespace Container3upfSg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddressGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Generator\AddressGenerator' shared autowired service.
     *
     * @return \App\Generator\AddressGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Generator/AddressGenerator.php';

        return $container->privates['App\\Generator\\AddressGenerator'] = new \App\Generator\AddressGenerator(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
