<?php

namespace Container3upfSg8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Handler\MessageHandler' shared autowired service.
     *
     * @return \App\Handler\MessageHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Handler/MessageHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Generator/Crypt.php';

        return $container->privates['App\\Handler\\MessageHandler'] = new \App\Handler\MessageHandler(($container->services['doctrine'] ?? $container->load('getDoctrineService')), ($container->privates['App\\Generator\\Mail'] ?? $container->load('getMailService')), new \App\Generator\Crypt(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
