<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1nJgEou\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1nJgEou/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1nJgEou.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1nJgEou\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1nJgEou\App_KernelDevDebugContainer([
    'container.build_hash' => '1nJgEou',
    'container.build_id' => '7f82c150',
    'container.build_time' => 1681315628,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1nJgEou');
