<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTEy2q0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTEy2q0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTEy2q0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTEy2q0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNTEy2q0\App_KernelDevDebugContainer([
    'container.build_hash' => 'NTEy2q0',
    'container.build_id' => 'de1e7fd3',
    'container.build_time' => 1682670495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTEy2q0');
