<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFiskiGn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFiskiGn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFiskiGn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFiskiGn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFiskiGn\App_KernelDevDebugContainer([
    'container.build_hash' => 'FiskiGn',
    'container.build_id' => '1a81ad6d',
    'container.build_time' => 1682001224,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFiskiGn');
